services:
  postgres:
    image: postgres:15-alpine
    container_name: product-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    ports:
      - "3000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: