server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:3000/product_db
    username: product_user
    password: product_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
